<?php
/**
 * @file
 * Uninstall functions for the getresponse module.
 */

/**
 * Implements hook_uninstall().
 */
function getresponse_uninstall() {
  variable_del('getresponse_api_key');
  variable_del('getresponse_webformid');
  variable_del('getresponse_comment_on');
  variable_del('getresponse_comment_label');
  variable_del('getresponse_webformurl');
  variable_del('getresponse_comment_campaign');
}
